### PR TITLE
Capable of pycryptodome

### PR DESCRIPTION
**Pull request by 9Mad-Max5**
Using the encode makes it possible to use pycrpytodome as Crypto instance.

### CODE REVIEW

**Comment by jamespo** [comment]
You need to add pycryptodome as a dependency in setup.py

**Comment by An0nimia** [comment]
@jamespo Why?

**Comment by jamespo** [comment]
Before I installed it manually I got:

   from Crypto.Hash import MD5
ModuleNotFoundError: No module named 'Crypto'

**Comment by An0nimia** [comment]
@jamespo apt-get install python3-crypto or pip3 install pycrypto

**Comment by jamespo** [comment]
I guess that will do it too - thanks.

**Comment by 9Mad-Max5** [comment]
Sorry. At the moment i start the pull request i actuall thought it would work. But it doesn´t i need to et back to pycrypto and the first line change. I didn´t made it till now to push it to my fork.

**Pull request closed without merging**
